### ISSUE TITLE
Please add running docker locally instructions to the README.md

### ISSUE THREAD

**Issue by pselvana** [victorchall/EveryDream2trainer#101]
Something like
`$ docker run -it -p 8888:8888 -p 6006:6006 --gpus all -e JUPYTER_PASSWORD=test1234 -t ghcr.io/victorchall/everydream2trainer:nightly`

That should let someone run the docker container locally since it requires GPU access for CUDA and the env variable JUPYTER_PASSWORD set to run Jupyter and Tensor Board exposing both ports.

**Comment by qslug** [comment]
I would add this, but I do not have a local GPU to test with. 

Probably also worth calling out that ED2 ships with two VS Code dev container configs, one with GPU support, one without. Opening up the project in a devcontainer will also spin up the container, and kick off Tensorflow and Jupyter, though again I have not been able to test this with GPU support.

**Comment by victorchall** [comment]
I tested it locally, it runs.  I'll add it.

Oddly the most convenient way seems to be to use that command to set it up, then shut it down, launch it with WSL because WSL  automounts all windows drives to /mnt while docker doesn't seem to want to do so despite me fidgeting with wsl.conf.

@pselvana you're always welcome to submit a PR to update docs as well.
