### ISSUE TITLE
[BUG] Using --disable_unet_training massively increases VRAM usage and crashes on 12gb VRAM

### ISSUE THREAD

**Issue by futurevessel** [victorchall/EveryDream2trainer#218]
Logically it would use less VRAM, like --disable_textenc_training does

**Comment by victorchall** [comment]
I don't see this behavior locally.  

You can set the learning rate on the Unet extremely low perhaps, like 1e-10 to compensate.  I cannot reproduce and 12GB is extremely tight on VRAM so any small difference in VRAM use may cause issues.  It could simply be you had Chrome open when you tried.

There is really no speed/vram advantage to actually disabling the Une training due to it being in the middle of the computational graph, between the prediction and the text encoder.  Grads are tracked regardless because its the only way to get grads into the text encoder, thus no VRAM savings.  

I would just set the Unet TE down to some low value and not use the feature if it is causing you problems.
