### ISSUE TITLE
Manually Patch Token Limit

### ISSUE THREAD

**Issue by CypherpunkSamurai** [victorchall/EveryDream2trainer#94]
# Manually Patch Token Limits
Hello :wave: I'm looking for a way to manually patch ED2 to support tokens > 75. Is this possible, and is it stable?

Thank you :)

**Comment by victorchall** [comment]
There are some trainers that do it, but I believe it can also cause problems because every new 77 token chunk will have maybe some bias to what tokens are early in that particular 77 token chunk, which is pretty arbitrary.   

Shuffling tags may make more sense.  You can read the shuffling doc for more information, but it will put in all the comma separated values into the first 77 token chunk randomly every epoch for each image.

Possible?  Yes, but I won't be adding it.  If you want to patch it yourself you can, but that's up to your skill and understanding, and not something I think I want in the core codebase.
